---
# tasks file for welcome-noobs
- name: Make a copy of project into ansible folder
  - copy:
    src: ~/welcome-noobs
    dest: /etc/ansible/roles/
    directory_mode: yes
    mode: 0644

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "/etc/ansible/roles/welcome-noobs/vars/{{ ansible_distribution }}.yml"
    - "/etc/ansible/roles/welcome-noobs/vars/{{ ansible_os_family }}.yml"

- name: Configure noobs admin syst computer's {{ ansible_pkg_mgr }}
  package:
    name: "{{ item }}"
  with_items:
    - "{{ _dependances }}"
    - "{{ _packages }}"

- name: execute package .deb
  apt: 
    deb: "{{ item }}"
  with_items:
    - "{{ _deb }}"
  when: ansible_os_family == "Debian"
